spring.application.name=eng-lens-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# GitHub API Token (set your personal access token here)
#github.token=
github.token=


# GitHub API Base URL (default is https://api.github.com)
#github.api.baseurl=https://api.github.com
github.api.baseurl=https://api.github.schneider-electric.com
